### ISSUE TITLE
Doesn't show up on Sony Bravia TV

### ISSUE THREAD

**Issue by lukechilds** [oeuillot/upnpserver-cli#1]
When I do `upnpserver -d /Films=/Users/lukechilds/Movies -n "node dlna test" --dlna` it won't show up as a media device on my Sony Smart TV. I've tried with and without `--strict`. It picks up other servers such as Plex, XBMC and BubbleUPnP without problems.

Interestingly, using BubbleUPnP on my phone I can see the server ok, If I set that as the server in BubbleUPnP and my TV as the renderer I can channel files through my phone and it all works.

Do you have any idea why this might be? I've been looking for a simple cli for upnp/dlna for a while and this is perfect, if it could work on my TV without the above work around that would be awesome.

Let me know if I can do anything else to help.

**Comment by lukechilds** [comment]
Just a bit more info:

Running

```
upnpserver -d /Films=`pwd` -n "node dlna test" --dlna --strict``
```

returns this:

```
NewItem id=0 parent=-1 name=root upnpClass=object.container container=true
Adding  1  repositories
Adding repository /Films
CDS: browseItem itemID=0 path='/' repositories.count=0
CDS: browseItem '/' returns 0 elements.
NewItem id=1 parent=0 name=Films upnpClass=object.container container=true
```

And then returns this every few seconds:

```
Request='/DeviceDescription.xml' from='192.168.1.227'
Request='/cms.xml' from='192.168.1.227'
Request='/cds.xml' from='192.168.1.227'
Request='/cds/control' from='192.168.1.227'
Call of soap action 'GetSortCapabilities': finished
```

`192.168.1.227` is my TV's IP address.

**Comment by oeuillot** [comment]
Hello can you add this issue to the upnpserver project not to the cli project !
Thanks.
